//using System.IO;
//using System.Reflection.Metadata;
//using iTextSharp.text; // Make sure to include iTextSharp  
//using iTextSharp.text.pdf;

//namespace Educational_Platform.Services
//{
//    public class PdfGeneratorService
//    {
//        public byte[] GenerateSamplePdf()
//        {
//            using (var memoryStream = new MemoryStream())
//            {
//                // Create a PDF writer that writes to the memory stream
//                PdfWriter writer = new PdfWriter(memoryStream);

//                // Create a PDF document
//                PdfDocument pdf = new PdfDocument(writer);

//                // Create a document for layout
//                Document document = new Document(pdf);

//                // Add content to the PDF
//                document.Add(new Paragraph("This is a sample PDF generated by PdfGeneratorService."));

//                document.Close(); // Close the document
//                return memoryStream.ToArray(); // Return the PDF as a byte array
//            }
//        }
//    }
//}